import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
  <div className="flex flex-col">
    {/* Navbar */}
    <Navbar />

    {/* Content area */}
    <div className="flex flex-1">
      <Sidebar  />
      <main className="flex-1 p-4 bg-gray-50 overflow-auto">
        {children}
      </main>
    </div>
  </div>
</body>

    </html>
  );
}
